[package]
name = "wry_ruby"
version = "0.1.0"
edition = "2021"
authors = ["gintama91 <b9-20@srkrec.edu.in>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.5.4" }
wry = "0.29.0"
gdk = "0.16.2"
gtk="0.16.2"